// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
function unauthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated." }],
    isError: true
  };
}
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's id, email and platform role (admin or student).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: roleRow } = await supabase.from("user_roles").select("role").eq("user_id", userId).maybeSingle();
    const { data: profile } = await supabase.from("profiles").select("full_name, phone, is_active").eq("user_id", userId).maybeSingle();
    const result = {
      user_id: userId,
      email: ctx.getUserEmail(),
      role: roleRow?.role ?? "student",
      full_name: profile?.full_name ?? null,
      is_active: profile?.is_active ?? true
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-courses.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
var list_courses_default = defineTool2({
  name: "list_courses",
  title: "List courses",
  description: "List the courses visible to the signed-in user (all courses for admins, enrolled courses for students).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    const { data, error } = await supabaseForUser(ctx).from("courses").select("id, title, description, quiz_duration_minutes, created_at").order("created_at", { ascending: false });
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { courses: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-lectures.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";
var list_lectures_default = defineTool3({
  name: "list_lectures",
  title: "List lectures",
  description: "List lectures the signed-in user can access, optionally filtered by course id.",
  inputSchema: {
    course_id: z.string().optional().describe("Optional course id to filter lectures by.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ course_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("lectures").select("id, title, description, course_id, duration_minutes, is_locked, created_at").order("created_at", { ascending: true });
    if (course_id) query = query.eq("course_id", course_id);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { lectures: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/watch-progress.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
var watch_progress_default = defineTool4({
  name: "get_watch_progress",
  title: "Get watch progress",
  description: "Get lecture watch progress rows visible to the signed-in user (own progress for students, all accessible rows for admins).",
  inputSchema: {
    lecture_id: z2.string().optional().describe("Optional lecture id filter."),
    student_id: z2.string().optional().describe("Optional student id filter (admins only; students see their own rows).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ lecture_id, student_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("watch_progress").select(
      "id, student_id, lecture_id, watched_seconds, total_duration, completion_percentage, open_count, last_watched_at"
    ).order("last_watched_at", { ascending: false }).limit(200);
    if (lecture_id) query = query.eq("lecture_id", lecture_id);
    if (student_id) query = query.eq("student_id", student_id);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { progress: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/quiz-attempts.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
var quiz_attempts_default = defineTool5({
  name: "list_quiz_attempts",
  title: "List quiz attempts",
  description: "List course quiz attempts visible to the signed-in user, optionally filtered by course id.",
  inputSchema: {
    course_id: z3.string().optional().describe("Optional course id filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ course_id }, ctx) => {
    if (!ctx.isAuthenticated()) return unauthenticated();
    let query = supabaseForUser(ctx).from("quiz_attempts").select("id, student_id, course_id, score, total_questions, completed_at, started_at").order("started_at", { ascending: false }).limit(200);
    if (course_id) query = query.eq("course_id", course_id);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { attempts: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "imdkwdppxqjckazzdvol";
var mcp_default = defineMcp({
  name: "gtc-lms-mcp",
  title: "GTC LMS",
  version: "0.1.0",
  instructions: "Tools for the GTC learning platform. Use `whoami` to identify the signed-in user, `list_courses` and `list_lectures` to browse content, `get_watch_progress` for lecture viewing progress, and `list_quiz_attempts` for quiz results. All data access respects the signed-in user's permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    whoami_default,
    list_courses_default,
    list_lectures_default,
    watch_progress_default,
    quiz_attempts_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
